In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
#array compuesto por ceros
#se usa para crear un esquema previo
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
#se da el valor inicio y fin y cuantos datos
#distribución ordenada
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [9]:
#crea una matriz con la diagonal principal en 1 y el resto en cero
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
#valores aleatoria
np.random.rand(4,4)

array([[0.67877964, 0.005665  , 0.56139948, 0.44350194],
       [0.17714877, 0.83797732, 0.85796595, 0.60736544],
       [0.41020817, 0.20117533, 0.88485213, 0.68822421],
       [0.81893912, 0.92350791, 0.60105429, 0.25158769]])

In [13]:
#entero aleatorio
np.random.randint(1,15)

13

In [15]:
#numeros aleatorios de 1 a 100 con una estructura de 10x10
np.random.randint(1,100,(10,10))

array([[ 5,  9, 69, 94, 26,  2, 35, 79, 89, 55],
       [21, 59, 48, 34, 19, 87,  1, 27, 18, 90],
       [ 9, 67, 43, 91, 31, 58,  7, 24, 35, 92],
       [45,  8, 74, 12, 47, 76, 52, 47,  3, 23],
       [54, 87, 35,  1,  2, 29, 65, 70, 22, 78],
       [84, 43, 77, 52, 95,  4, 19, 67, 61, 65],
       [ 6, 23, 79, 75,  3, 89, 79, 70, 23, 82],
       [67, 82, 38, 23, 55, 58, 79, 59, 16, 92],
       [ 5, 87, 51,  4, 98, 34, 48, 40, 66, 65],
       [53, 36, 78, 60, 16,  9, 91, 41, 39, 88]])