In [1]:
import numpy as np

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

Escalar con 0 dimensiones

In [4]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [5]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [7]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

una matriz sobre otra matriz

## Agregar o eliminar dimensiones

In [8]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [12]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

expande una dimensión en las filas

In [14]:
#eliminar
#squeeze lo que hace es comprimir al número de dimensiones que 
#no se estén usando
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
