In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,20,10)

In [5]:
matriz = arr.reshape(2,5)
matriz

array([[15,  5, 17,  3,  5],
       [ 1, 10,  6,  5, 18]])

In [7]:
arr

array([15,  5, 17,  3,  5,  1, 10,  6,  5, 18])

In [6]:
# numero mayor
arr.max()

18

In [8]:
matriz.max()

18

In [9]:
# numero mayor solo por el eje 1, filas
matriz.max(1)

array([17, 18])

In [10]:
# numero mayor solo por el eje 0, columnas
matriz.max(0)

array([15, 10, 17,  5, 18])

In [11]:
# indice en donde se encuentra el valor más grande del array
arr.argmax()

9

In [12]:
# el indice donde se encuentra el numero mayor por cada columna
matriz.argmax(0)

array([0, 1, 0, 1, 1], dtype=int64)

In [14]:
arr.min()

1

In [15]:
matriz.min(0)

array([1, 5, 6, 3, 5])

In [17]:
arr.argmin()

5

In [16]:
matriz.argmin(1)

array([3, 0], dtype=int64)