In [1]:
import numpy as np

Recordar:
- 0 -> columnas
- 1 -> filas

In [2]:
arr = np.random.randint(1,20,10)

In [3]:
matriz = arr.reshape(2,5)
matriz

array([[10, 19, 14,  8, 15],
       [ 4, 13,  8, 15, 12]])

In [4]:
arr

array([10, 19, 14,  8, 15,  4, 13,  8, 15, 12])

In [5]:
# numero mayor
arr.max()

19

In [6]:
matriz.max()

19

In [7]:
# numero mayor solo por el eje 1, filas
matriz.max(1)

array([19, 15])

In [8]:
# numero mayor solo por el eje 0, columnas
matriz.max(0)

array([10, 19, 14, 15, 15])

In [9]:
# indice en donde se encuentra el valor más grande del array
arr.argmax()

1

In [10]:
# el indice donde se encuentra el numero mayor por cada columna
matriz.argmax(0)

array([0, 0, 0, 1, 0], dtype=int64)

In [11]:
arr.min()

4

In [12]:
matriz.min(0)

array([ 4, 13,  8,  8, 12])

In [13]:
arr.argmin()

5

In [14]:
matriz.argmin(1)

array([3, 0], dtype=int64)

In [16]:
arr

array([10, 19, 14,  8, 15,  4, 13,  8, 15, 12])

In [15]:
# de un pico al otro pico, del pico màs bajo al más alto me da la diferencia
# el valor màs pequeño 4 y el más alto 9 = 5
arr.ptp()

15

In [17]:
# distancia por el eje 0
matriz.ptp(0)

array([6, 6, 6, 7, 3])

In [20]:
# percentil especifica el percentil qu estoy trabajando
# cual es el valor que se encuentra en la mitad, percentil 50 mediana
# percentil 0, es el valor màs bajo
np.percentile(arr, 50)

12.5

In [21]:
# entrega la mediana
np.median(arr)

12.5

In [22]:
# mediana a nivel de matriz eje 1
np.median(matriz, 1)

array([14., 12.])

In [23]:
# desviación estandar, y elevado al cuadrado es igual a la varianza
np.std(arr) 

4.142463035441596

In [24]:
np.var(arr)

17.16

In [25]:
np.mean(arr)

11.8

In [30]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
a

array([[1, 2],
       [3, 4]])

In [31]:
#
np.concatenate((a,b),0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [32]:
a.ndim

2

In [33]:
b.ndim

1

In [34]:
b = np.expand_dims(b,axis=0)

In [35]:
#
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
# si queremos por el eje 1
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [37]:
b.T

array([[5],
       [6]])

In [39]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])